### PR TITLE
Upgraded tooling

### PR DESCRIPTION
**Pull request by DaemonBeast**

### CODE REVIEW

**Review by Ecorous — CHANGES_REQUESTED** [review]
Why have you excluded the references?

**Comment by DaemonBeast** [comment]
> Why have you excluded the references?

@ExoPlant References are now fetched from the BepInEx NuGet: <https://nuget.bepinex.dev/>.

**Comment by Ecorous** [comment]
All of them? Including MyScriptAssembly.dll?

**Comment by Ecorous** [comment]
And the Unity dlls?

**Comment by DaemonBeast** [comment]
Yes, the game libs are in the `SpiderHeck.GameLibs` package and the Unity dlls are in the `UnityEngine.Modules` package. In addition, BepInEx and Harmony dlls are in the `BepInEx.Unity` package (try compiling it if you don't believe me 😏).

**Pull request merged**
